# Generated by Django 3.0.2 on 2020-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
